#!/bin/bash
# $1 the rss url (optional), $2 the directory to put all the image in
# NOTE: $2 will be cleaned first

# Can handle normal enclosures and also media:content like reddit uses

CURL="curl -s"

if [ -d "$1" ]; then 
    DIR="${1%/}"
else
    DIR="${2%/}"
fi

LIMIT=
if [ -n $3 ]; then
    LIMIT=$3
fi

[ -z "$DIR" ] && exit 1

RSS="$DIR/rss"
RSS_TMP="`mktemp`"
URL_FILE="$DIR/url"

URL="`cat "$URL_FILE" 2>/dev/null`"
[ -z "$URL" ] && URL="$1"

if [ -n "$URL" ]; then
    $CURL "$URL" -o "$RSS_TMP"
    ## check if the rss contain at least an enclosure
    if fgrep -m1 -e '<enclosure url=' -e '<media:content url=' "$RSS_TMP" && \
        (! [ -e "$RSS" ] || ! diff "$RSS_TMP" "$RSS"); then

        mkdir -p "$DIR"
        rm -rf "$DIR/"*
        cp "$RSS_TMP" "$RSS"
        echo "$URL" > "$URL_FILE"
        COUNTER=0

        sed -n 's/.*<\(media:content\|enclosure\).*url="\([^"]*\)".*/\2/p' \
        "$RSS" | while read line; do
            if [[ -n "$LIMIT" ]] && [[ $COUNTER -ge $LIMIT ]]; then
                exit 0
            fi
            name="${line##*/}"
            name="${name%%.*}"
            ext="${line##*.}"
            ext="${ext%%[^a-zA-Z]*}"
            $CURL "$line" -o "$DIR/$name.$ext"
            let COUNTER=COUNTER+1 
        done
    fi
fi
rm "$RSS_TMP"
